trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: ci
    jobs:
      - job: DockerBuildAndPush
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'metargrab container registry connection'
            repository: 'metargrab'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'